### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by cristinanahid** [meme/hotwax#13]
Do you know how hotwax performs in comparison to tools based on dynamorio like afl-dynamorio? Or the performance of stalker compared to dynamorio tracing in general?

**Comment by vanhauser-thc** [comment]
frida has about x2 the speed compared to user mode qemu fuzzing.
dynamrio is about 10x slower than qemu ... so expect a 20x+ slower speed with afl-dynamorio compared to frida.

the fastest you can have is either a binary rewrite (e.g. retrowrite) or if you can use qemu_mode with persistent + in-memory test cases

**Comment by meme** [comment]
The plan is to provide better benchmarking info once we integrate the prefetch caching #10.
